### ISSUE TITLE
Panics if /usr/share/dict/words not found

### ISSUE THREAD

**Issue by focusaurus** [maaslalani/typer#16]
**Describe the bug**
Running with no args on arch linux I don't have the "words" package installed. I get a panic. Not a big deal and easily worked around but a clear error message or even a small fallback list of words baked into the exe might be more graceful.

**To Reproduce**
Install typer on arch linux without the "words" package. Run it with no arguments.

**Expected behavior**
Fall back to some other word list, or print a simple error message.

**Screenshots**
```
❯ typer
panic: open /usr/share/dict/words: no such file or directory

goroutine 1 [running]:
github.com/tjarratt/babble.readAvailableDictionary()
        /home/plyons/go/pkg/mod/github.com/tjarratt/babble@v0.0.0-20191209142150-eecdf8c2339d/babble_unix.go:14 +0x9c
github.com/tjarratt/babble.NewBabbler(...)
        /home/plyons/go/pkg/mod/github.com/tjarratt/babble@v0.0.0-20191209142150-eecdf8c2339d/babble.go:22
github.com/maaslalani/typer/pkg/utility.RandomWords(0x14)
        /home/plyons/go/pkg/mod/github.com/maaslalani/typer@v0.0.0-20211105034731-4be028fe3127/pkg/utility/utility.go:19 +0x6f
github.com/maaslalani/typer/pkg/typer.FromRandom(0xc000010010, 0x6f95c8)
        /home/plyons/go/pkg/mod/github.com/maaslalani/typer@v0.0.0-20211105034731-4be028fe3127/pkg/typer/typer.go:54 +0x1e
github.com/maaslalani/typer/cmd.glob..func1(0x94d660, {0x6f6873, 0x0, 0x0})
        /home/plyons/go/pkg/mod/github.com/maaslalani/typer@v0.0.0-20211105034731-4be028fe3127/cmd/root.go:58 +0x26b
github.com/spf13/cobra.(*Command).execute(0x94d660, {0xc000012200, 0x0, 0x0})
        /home/plyons/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x94d660)
        /home/plyons/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
        /home/plyons/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/maaslalani/typer/cmd.Execute()
        /home/plyons/go/pkg/mod/github.com/maaslalani/typer@v0.0.0-20211105034731-4be028fe3127/cmd/root.go:68 +0x25
main.main()
        /home/plyons/go/pkg/mod/github.com/maaslalani/typer@v0.0.0-20211105034731-4be028fe3127/main.go:6 +0x17
```
**Desktop (please complete the following information):**
 - OS: arch linux

**Additional context**

**Comment by maaslalani** [comment]
Hey! Thanks so much for filing this issue, totally agreed on the fallback list or nice error warning, always better than panics :)

**Comment by focusaurus** [comment]
Maybe this is a bug in the babble api though since it seems to panic and not return an error.

**Comment by happyRip** [comment]
An issue could be opened in [`tjarratt/babble`](https://github.com/tjarratt/babble) and while that is being resolved a manual check could be performed if `/usr/share/dict/words` exists on `typer`'s end as a temporary fix.

**Comment by maaslalani** [comment]
Hey! I've removed `babble` as a dependency in favour of more [common words](https://github.com/tyler-smith/go-bip39/blob/master/wordlists/english.go)

Hopefully that should solve this issue, but please reopen if it doesn't.
