### ISSUE TITLE
Prodive own UI

### ISSUE THREAD

**Issue by AgentNemo** [maaslalani/typer#22]
**Is your feature request related to a problem? Please describe.**
I want to use the business logic you have implemented but do not want to use it in the terminal. I want to build my own UI arround the logic

**Describe the solution you'd like**
I would like an Interface for UI Outputs which can be injected

Does anyone have some suggestions ? I did a quick code check and could not determine a clear seperation from business logic and UI representation. Am I wrong ?

**Comment by maaslalani** [comment]
If you do not want to use it in the terminal then I don't think the right solution is to use the logic of `typer`. I would guess 90% of the code is mainly for Text-based User Interface (TUI) and the only logic that can be shared for a non-TUI program is the sentence generation.

Additionally, there are great Web UI typing solutions that I would recommend using such as:
* https://monkeytype.com
* https://www.keybr.com/
