### ISSUE TITLE
Use our own random word generator

### ISSUE THREAD

**Issue by maaslalani** [maaslalani/typer#5]
Replace https://github.com/tjarratt/babble with a more domain specific word generator.

Our replacement should:
- [ ] Create sentences (with punctuation)
- [ ] Have configurable word length (character limit)
- [ ] Priority letters (if we want all words to include a certain letter for training like keybr.com does.

**Comment by lcw** [comment]
It would be nice to have an option for bigrams, trigrams, and tetragrams similar to <https://ranelpadon.github.io/ngram-type/>.
